# Generated by Django 3.0.5 on 2021-01-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210120_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='title_id',
        ),
    ]
